- id: check-added-large-files
  name: check for added large files
  description: prevents giant files from being committed.
  entry: check-added-large-files
  language: python
- id: check-ast
  name: check python ast
  description: simply checks whether the files parse as valid python.
  entry: check-ast
  language: python
  types: [python]
- id: check-builtin-literals
  name: check builtin type constructor use
  description: requires literal syntax when initializing empty or zero python builtin types.
  entry: check-builtin-literals
  language: python
  types: [python]
- id: check-case-conflict
  name: check for case conflicts
  description: checks for files that would conflict in case-insensitive filesystems.
  entry: check-case-conflict
  language: python
- id: check-docstring-first
  name: check docstring is first
  description: checks a common error of defining a docstring after code.
  entry: check-docstring-first
  language: python
  types: [python]
- id: check-executables-have-shebangs
  name: check that executables have shebangs
  description: ensures that (non-binary) executables have a shebang.
  entry: check-executables-have-shebangs
  language: python
  types: [text, executable]
  stages: [commit, push, manual]
- id: check-json
  name: check json
  description: checks json files for parseable syntax.
  entry: check-json
  language: python
  types: [json]
- id: check-shebang-scripts-are-executable
  name: check that scripts with shebangs are executable
  description: ensures that (non-binary) files with a shebang are executable.
  entry: check-shebang-scripts-are-executable
  language: python
  types: [text]
  stages: [commit, push, manual]
- id: pretty-format-json
  name: pretty format json
  description: sets a standard for formatting json files.
  entry: pretty-format-json
  language: python
  types: [json]
- id: check-merge-conflict
  name: check for merge conflicts
  description: checks for files that contain merge conflict strings.
  entry: check-merge-conflict
  language: python
  types: [text]
- id: check-symlinks
  name: check for broken symlinks
  description: checks for symlinks which do not point to anything.
  entry: check-symlinks
  language: python
  types: [symlink]
- id: check-toml
  name: check toml
  description: checks toml files for parseable syntax.
  entry: check-toml
  language: python
  types: [toml]
- id: check-yaml
  name: check yaml
  description: checks yaml files for parseable syntax.
  entry: check-yaml
  language: python
  types: [yaml]
- id: debug-statements
  name: debug statements (python)
  description: checks for debugger imports and py37+ `breakpoint()` calls in python source.
  entry: debug-statement-hook
  language: python
  types: [python]
- id: detect-private-key
  name: detect private key
  description: detects the presence of private keys.
  entry: detect-private-key
  language: python
  types: [text]
- id: end-of-file-fixer
  name: fix end of files
  description: ensures that a file is either empty, or ends with one newline.
  entry: end-of-file-fixer
  language: python
  types: [text]
  stages: [commit, push, manual]
- id: name-tests-test
  name: python tests naming
  description: this verifies that test files are named correctly.
  entry: name-tests-test
  language: python
  files: (^|/)tests/.+\.py$
- id: requirements-txt-fixer
  name: fix requirements.txt
  description: sorts entries in requirements.txt.
  entry: requirements-txt-fixer
  language: python
  files: requirements.*\.txt$
- id: trailing-whitespace
  name: trim trailing whitespace
  description: trims trailing whitespace.
  entry: trailing-whitespace-fixer
  language: python
  types: [text]
  stages: [commit, push, manual]
